# SPDX-License-Identifier: AGPL-3.0-or-later
"""Regression tests for the Anlord Abliterator product name."""

from pathlib import Path

from anlord.evaluation.comparison import ComparisonResult
from anlord.reports.formatters import format_csv
from anlord.reports.generator import ReportGenerator


def test_readme_does_not_expand_anlord_as_an_acronym():
    readme = Path(__file__).parents[1].joinpath("README.md").read_text(encoding="utf-8")

    assert readme.startswith("# Anlord Abliterator\n")
    assert "**A**bliteration → **N**ormalization" not in readme


def test_reports_use_full_product_name(tmp_path):
    comparison = ComparisonResult(model_id="example/model")

    assert "Anlord Abliterator Report" in format_csv(comparison)
    html = ReportGenerator(tmp_path)._build_html(comparison)
    assert "<h1>Anlord Abliterator Report</h1>" in html
    assert "Generated by Anlord Abliterator" in html
